=== EBISPOT/biomedbridges/query-interface/src/main/webapp/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://wwwdev.ebi.ac.uk/fgpt/toolsui/schema" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Tools" type="sch:ToolsType" xmlns:sch="http://wwwdev.ebi.ac.uk/fgpt/toolsui/schema"/>

    <xs:complexType name="ToolType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">

            <xs:element type="xs:string" name="Name" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="SoftwareName" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="Citations"/>
            <xs:element type="xs:string" name="Collection"/>
            <xs:element type="xs:string" name="ContactName"/>
            <xs:element type="xs:string" name="ContactPage"/>
            <xs:element type="xs:string" name="Contributors"/>
            <xs:element type="xs:string" name="Description" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="Developer"/>
            <xs:element type="xs:string" name="DeveloperInterface"/>
            <xs:element type="xs:string" name="DocsCommandLine"/>
            <xs:element type="xs:string" name="DocsHome"/>
            <xs:element type="xs:string" name="DocsREST"/>
            <xs:element type="xs:string" name="DocsSOAP"/>
            <xs:element type="xs:string" name="DocsSPARQL"/>
            <xs:element type="xs:string" name="Download"/>
            <xs:element type="xs:string" name="DRCAT"/>
            <xs:element type="xs:string" name="FunctionHandle"/>
            <xs:element type="xs:string" name="Functions"/>
            <xs:element type="xs:string" name="FunctionsURI"/>
            <xs:element type="xs:string" name="Funding"/>
            <xs:element type="xs:string" name="Helpdesk"/>
            <xs:element type="xs:string" name="Homepage"/>
            <xs:element type="xs:string" name="Infrastructures"/>
            <xs:element type="xs:string" name="InputFormats"/>
            <xs:element type="xs:string" name="InputTypes"/>
            <xs:element type="xs:string" name="InputTypesURI"/>
            <xs:element type="xs:string" name="Institutions"/>
            <xs:element type="xs:string" name="Interfaces"/>
            <xs:element type="xs:string" name="InterfacesCommandline"/>
            <xs:element type="xs:string" name="InterfacesDesktopGUI"/>
            <xs:element type="xs:string" name="InterfacesOther"/>
            <xs:element type="xs:string" name="InterfacesRESTAPI"/>
            <xs:element type="xs:string" name="InterfacesSOAPAPI"/>
            <xs:element type="xs:string" name="InterfacesJavaAPI"/>
            <xs:element type="xs:string" name="InterfacesWebUI"/>
            <xs:element type="xs:string" name="InterfacesBiomart"/>
            <xs:element type="xs:string" name="InterfacesURI"/>
            <xs:element type="xs:string" name="InterfacesManualDownload"/>
            <xs:element type="xs:string" name="License"/>
            <xs:element type="xs:string" name="LicenseURI"/>
            <xs:element type="xs:string" name="OutputFormats"/>
            <xs:element type="xs:string" name="OutputTypes"/>
            <xs:element type="xs:string" name="OutputTypesURI"/>
            <xs:element type="xs:string" name="PlatformsLinux"/>
            <xs:element type="xs:string" name="PlatformsOSX"/>
            <xs:element type="xs:string" name="PlatformsWindows"/>
            <xs:element type="xs:string" name="Provider"/>
            <xs:element type="xs:string" name="PublicationsPrimary"/>
            <xs:element type="xs:string" name="PublicationsOther"/>
            <xs:element type="xs:string" name="SearchTerms"/>
            <xs:element type="xs:string" name="Tags"/>
            <xs:element type="xs:string" name="WSDL"/>
            <xs:element type="xs:string" name="TagsURI"/>
            <xs:element type="xs:string" name="TermsOfUse"/>
            <xs:element type="xs:string" name="Topics" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="TopicsURI"/>
            <xs:element type="xs:string" name="Type" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="Version"/>

            <xs:element name="Maturity">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Alpha "/>
                        <xs:enumeration value="Beta "/>
                        <xs:enumeration value="Production "/>
                        <xs:enumeration value="In development "/>
                        <xs:enumeration value="In testing "/>
                        <xs:enumeration value="not specified "/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="Platforms">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="not specified "/>
                        <xs:enumeration value="Unix "/>
                        <xs:enumeration value="Windows "/>
                        <xs:enumeration value="Linux "/>
                        <xs:enumeration value="OS X "/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="Languages">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="not specified "/>
                        <xs:enumeration value="Java "/>
                        <xs:enumeration value="Perl "/>
                        <xs:enumeration value="Python "/>
                        <xs:enumeration value="R "/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="WorkPackages">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="not specified "/>
                        <xs:enumeration value="WP10 "/>
                        <xs:enumeration value="WP6 "/>
                        <xs:enumeration value="WP3 "/>
                        <xs:enumeration value="WP7 "/>
                        <xs:enumeration value="WP8 "/>
                        <xs:enumeration value="WP9 "/>
                        <xs:enumeration value="WP4 "/>
                        <xs:enumeration value="WP5 "/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="Cost">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="not specified "/>
                        <xs:enumeration value="Free "/>
                        <xs:enumeration value="Free for non profit "/>
                        <xs:enumeration value="Free for academic use "/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

        </xs:choice>
        <xs:attribute type="xs:string" name="toolid" use="optional"/>
    </xs:complexType>

    <xs:complexType name="ToolsType">
        <xs:sequence>
            <xs:element type="sch:ToolType"
                        name="Tool"
                        maxOccurs="unbounded"
                        minOccurs="0"
                        xmlns:sch="http://wwwdev.ebi.ac.uk/fgpt/toolsui/schema">
                <xs:annotation>
                    <xs:documentation>&lt;Tools xmlns="http://wwwdev.ebi.ac.uk/fgpt/toolsui/schema"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xsi:schemaLocation="http://wwwdev.ebi.ac.uk/fgpt/toolsui/schemahttp://wwwdev.ebi.ac.uk/fgpt/toolsui/2014/10/29/schema.xsd"></xs:documentation>
                </xs:annotation>
                <xs:unique name="testUnique">
                    <xs:selector xpath="tool"/>
                    <xs:field xpath="name"/>
                </xs:unique>
            </xs:element>

        </xs:sequence>

    </xs:complexType>

</xs:schema>

=== EBISPOT/biomedbridges/query-interface/src/main/webapp/data/gotools.xml
<Tools xmlns="http://www.ebi.ac.uk/fgpt/toolsui/schema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        >
    xsi:schemaLocation="
    http://www.ebi.ac.uk/fgpt/toolsui/schema
    http://www.ebi.ac.uk/fgpt/toolsui/2014/10/29/schema.xsd
    ">
    <Tool toolid='nlx_149321'>
        <Name>APID: Agile Protein Interaction DataAnalyzer|http://bioinfow.dep.usal.es/apid</Name>
        <Type>Tool</Type>
        <Collection>GO Tools</Collection>
        <Description>Integrate and analyze in a unified and comparative platform known information about protein-protein
            interactions demonstrated by specific small-scale or large-scale experimental methods.
        </Description>
        <Institutions>University of Salamanca; Salamanca; Spain</Institutions>
        <Funding>PI030920, PI061153, SA104/03, CSI03A06, BOCyL no. 119, EDU/777/2005</Funding>
        <Infrastructures>Spanish Ministerio de Sanidad y Consumo, ISCIII, Junta de Castilla y Leon, Fundacion BBVA
        </Infrastructures>
        <Publications>PMID:16845013, 17644818</Publications>
        <Citations>73</Citations>
        <Tags>protein-protein interaction analysis, protein-protein interaction, protein interaction, Protein,
            interaction, cluster coefficient, Gene Ontology, functional environment, environment enrichment, Gene
            Ontology overlapping, Pfam domain-domain interaction, Visualization, domain-domain interaction, GO
            Environment, GO Environment Enrichment, interactome, graph
        </Tags>
    </Tool>
    <Tool toolid='nif-0000-20935'>
        <Name>AmiGO|http://amigo.geneontology.org/cgi-bin/amigo/go.cgi</Name>
        <Type>Tool</Type>
        <Collection>GO Tools</Collection>
        <Description>Official Web-based set tools for searching and browsing the Gene Ontology database, which consists
            of a controlled vocabulary of terms covering biological concepts, and a large number of genes or gene
            products whose attributes have been annotated using GO terms.
        </Description>
        <Institutions>GO</Institutions>
        <Funding>P41 5P41HG002273-08</Funding>
        <Infrastructures>NHGRI</Infrastructures>
        <Publications>PMID:19033274</Publications>
        <Citations>237</Citations>
        <Tags>gene, gene ontology, gene product, annotation, bioinformatics, biological, blast, concept, protein, search
            engine, visualization, Ontology, Browser, ontology or annotation browser, ontology or annotation search
            engine, ontology or annotation visualization, slimmer-type tool, term enrichment, other analysis
        </Tags>
    </Tool>
    <Tool toolid='nlx_149208'>
        <Name>Avadis|http://www.avadis-ngs.com</Name>
        <Type>Tool</Type>
        <Collection>GO Tools</Collection>
        <Description>A data analysis and visualization tool for gene expression data. Avadis has a built-in Gene
            Ontology browser to view ontology hierarchies.
        </Description>
        <Institutions>Strand Life Sciences</Institutions>
        <Tags>gene expression, statistical analysis, Gene Ontology, browser, ontology, gene, text mining, statistical
            mining, modelling, analysis, algorithm, microarray, QSAR modelling, biological network, PCA, ANOVA, T-test,
            clustering, classification, regression
        </Tags>
    </Tool>
    <Tool toolid='nif-0000-30144'>
        <Name>Babelomics 4: Gene Expression and Functional Profiling Analysis Suite|http://babelomics.bioinfo.cipf.es
        </Name>
        <Type>Suite</Type>
        <Collection>GO Tools</Collection>
        <Description>Babelomics is a complete suite of web tools for the functional profiling of genome scale
            experiments, with new and improved methods as well as more types of functional definitions.
        </Description>
        <Institutions>CIPF Bioinformatics and Genomics Department</Institutions>
        <Funding>BIO2008-04212, CEN-2008-1002, RD06/0020/1019</Funding>
        <Infrastructures>Spanish Ministry of Science and Innovation, Red Temtica de Investigacin Cooperativa en Cancer,
            Instituto de Salud Carlos III
        </Infrastructures>
        <Publications>PMID:20478823, 18515841, 16845052, 14990455, 15980512, 17478504</Publications>
        <Citations>72</Citations>
        <Tags>Integration, Platform, Analysis, Transcriptomics, Proteomics, Genomics, Normalization, Clustering, Tool,
            Environment, Gene, MiRNA, Protein, Interaction, Text mining, Genotyping, Bioentity, Functional profiling,
            Statistical analysis, Functional annotation, Regulatory motif, Microarray, FatiGO, Biclustering,
            NetworkMiner, GEPAS
        </Tags>
    </Tool>
    <Tool toolid='nlx_149196'>
        <Name>BiNGO: A Biological Networks Gene Ontology tool|http://www.psb.ugent.be/cbd/papers/BiNGO/Home.html</Name>
        <Type>Tool</Type>
        <Collection>GO Tools</Collection>
        <Description>Determine which Gene Ontology (GO) terms are significantly overrepresented in a set of genes. BiNGO
            can be used either on a list of genes, pasted as text, or interactively on subgraphs of biological networks
            visualized in Cytoscape.
        </Description>
        <Institutions>Ghent University; Ghent; Belgium</Institutions>
        <Publications>PMID:15972284</Publications>
        <Citations>575</Citations>
        <Tags>Gene Ontology, Gene, Ontology, statistical analysis, term enrichment, biological network, Plugin</Tags>
    </Tool>
    <Tool toolid='nif-0000-30188'>
        <Name>BioPerl|http://www.bioperl.org</Name>
        <Type>Library</Type>
        <Collection>GO Tools</Collection>
        <Description>BioPerl is a community effort to produce Perl code which is useful in biology. This toolkit of perl
            modules is useful in building bioinformatics solutions in Perl.
        </Description>
        <Institutions>Duke University; North Carolina; USA, European Bioinformatics Institute</Institutions>
        <Funding>T32 GM0775422, K22 HG00056, K22 HG-00064-01, HG00739, P41HG02223</Funding>
        <Infrastructures>Association for the Promotion of Science and Humanities in Germany, Open Bioinformatics
            Foundation, NIH, NHGRI, EMBL, Wyeth Research
        </Infrastructures>
        <Publications>PMID:12368254</Publications>
        <Citations>643</Citations>
        <Tags>Perl, Biology, Ontology, Library, Sequence, Analysis, Computational, Application, Pipeline,
            bioinformatics, Sequence, annotation, Module, Life science, Python, Java, Genome, software library, Parse,
            Manipulate
        </Tags>
    </Tool>
    <Tool toolid='nif-0000-10445'>
        <Name>Bioconductor|http://www.bioconductor.org/</Name>
        <Type>Package</Type>
        <Collection>GO Tools</Collection>
        <Description>Open source, open development software project providing tools for the analysis and comprehension
            of high-throughput genomic data. It is based primarily on the R programming language.
        </Description>
        <Institutions>Fred Hutchinson Cancer Research Center</Institutions>
        <Funding>#1R33 HG002708</Funding>
        <Infrastructures>NIH, Catt Family Foundation, Dana-Farber Cancer Institute</Infrastructures>
        <Publications>PMID:15461798</Publications>
        <Citations>3340</Citations>
        <Tags>analysis, biological, development, genomic, graphical, metadata, microarray, software, statistical,
            variant, annotation, High throughput assay, Sequence data, Sequence, Flow, Gene, term enrichment, text
            mining, Genetic, ontology or annotation browser, ontology or annotation search engine, ontology or
            annotation visualization, database or data warehouse, software library, statistical analysis, other
            analysis, Flexible integration of GO into statistical analysis and comprehension of high-throughput genetic
            data, browser, search engine, visualization, high-throughput, genetics, GenAddiction Tool
        </Tags>
    </Tool>
    <Tool toolid='nlx_149335'>
        <Name>Blast2GO|http://www.blast2go.com/b2ghome</Name>
        <Type>Tool</Type>
        <Collection>GO Tools</Collection>
        <Description>Blast2GO (B2G) joins in one universal application similarity search based GO annotation and
            functional analysis. B2G offers the possibility of direct statistical analysis on gene function information
            and visualization of relevant functional features on a highlighted GO direct acyclic graph (DAG).
        </Description>
        <Institutions>Principe Felipe Research Centre; Valencia; Spain</Institutions>
        <Funding>GEN 2001 - 4885-C05-03, FP6-2002-LIFESCIHEALTH 503094</Funding>
        <Infrastructures>MCyT, eTumour Project</Infrastructures>
        <Publications>PMID:16081474</Publications>
        <Citations>1078</Citations>
        <Tags>annotation, visualization, analysis, functional genomics, editor, statistical analysis, slimmer-type tool,
            ontology or annotation editor, functional analysis, direct acyclic graph, analysis, high throughput,
            functional genomics
        </Tags>
    </Tool>
    <Tool toolid='nlx_149193'>
        <Name>Blip: Biomedical Logic Programming|http://www.blipkit.org/</Name>
        <Type>Framework</Type>
        <Collection>GO Tools</Collection>
        <Description>Biomedical Logical Programming (Blip) is a research-oriented deductive database and prolog
            application library for handling biological and biomedical data. It includes packages for advanced querying
            of ontologies and annotations.
        </Description>
        <Institutions>Berkeley Bioinformatics Open-Source Projects,</Institutions>
        <Tags>biology, biomedical, ontology, annotation, software library, bioinformatics, module</Tags>
    </Tool>
    <Tool toolid='nlx_149116'>
